### PR TITLE
Made the read me better

### PR DESCRIPTION
**Pull request by Iweisc**

### CODE REVIEW

**Comment by Iweisc** [comment]
I added some extra features to the readme
If u want me to farther more improve it i can 
Thanks Zawad,
Best Regards

**Comment by Iweisc** [comment]
@abdullahsohailcs

**Comment by abdullahsohailcs** [comment]
These changes are Amazing! Thanks a lot. 😃

**Comment by Iweisc** [comment]
Thank u too

**Comment by Iweisc** [comment]
I am looking forward to collab on projects

**Comment by Iweisc** [comment]
and btw i am 13 years old lol

**Comment by abdullahsohailcs** [comment]
That's cool. Will let you know. Keeping progressing!

**Pull request merged**
